name: Check M3U Playlist

on:
  workflow_dispatch:

jobs:
  check-streams:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install requirements
      run: pip install requests

    - name: Run stream checker
      run: python check_m3u.py
